language: node_js

node_js:
 - lts/*

install:
 - npm install -g hexo-cli
 - npm install

script:
 - hexo clean
 - hexo generate
 
cache: yarn

# deploy:
#  provider: pages
#  skip_cleanup: true
#  keep_history: true
#  local_dir: dist
#  target_branch: master
#  on:
#   branch: gh-pages
#  github_token: $GITHUB_TOKEN