language: node_js
node_js:
  - lts/*
# 默认是yarn, 如果有yarn.lock的话
install:
  - yarn
# 默认是 yarn test
script:
  - yarn build
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: gh-pages
  github_token: $GITHUB_TOKEN