language: node_js
node_js:
- lts/*
# 默认是yarn, 如果有yarn.lock的话
install:
- yarn
# 默认是 yarn test
script:
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  target_branch: master
  on:
    branch: gh-pages
  github-token: $GITHUB_TOKEN