# 指定语言环境
language: node_js

# 指定node_js版本
node_js:
 - "12"

branches:
 only:
  - gh-pages

# Start: Build Lifecycle
install:
 - npm install -g hexo-cli
 - npm install

# 执行清缓存，生成网页操作
script:
 - hexo clean
 - hexo generate
 - npm run deploy