# 指定语言环境
language: node_js

# 指定node_js版本
node_js:
 - "10"

branches:
 only:
  - gh-pages

# Start: Build Lifecycle
install:
 - npm install -g hexo-cli
 - npm install

# 执行清缓存，生成网页操作
script:
 - hexo clean
 - hexo generate
# deploy:
#  provider: pages
#  skip_cleanup: true
#  keep_history: true
#  local_dir: dist
#  target_branch: master
#  on:
#   branch: gh-pages
#  github_token: $GITHUB_TOKEN